import { Router } from "express";
import { router as adminRouter } from "./admin.routes";
import { router as authRouter } from "./auth.routes";
import { router as bookingsRouter } from "./bookings.routes";
import { router as casesRouter } from "./cases.routes";
import { router as discoveryRouter } from "./discovery.routes";
import { router as favoritesRouter } from "./favorites.routes";
import { router as healthRouter } from "./health.routes";
import { router as messagingRouter } from "./messaging.routes";
import { router as notificationsRouter } from "./notifications.routes";
import { router as photographerRouter } from "./photographer.routes";
import { router as portfolioRouter } from "./portfolio.routes";
import { router as reviewsRouter } from "./reviews.routes";
import { router as supportRouter } from "./support.routes";

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(authRouter);
apiRouter.use(discoveryRouter);
apiRouter.use(photographerRouter);
apiRouter.use(bookingsRouter);
apiRouter.use(messagingRouter);
apiRouter.use(casesRouter);
apiRouter.use(portfolioRouter);
apiRouter.use(reviewsRouter);
apiRouter.use(favoritesRouter);
apiRouter.use(notificationsRouter);
apiRouter.use(supportRouter);
apiRouter.use(adminRouter);
