#!/usr/bin/env bash
#===============================================================================
# Git Automation Script
# Usage: ./scripts/git-automate.sh <branch-name> <commit-message> [files...]
#
# Creates a branch, stages files, commits, pushes, and creates a PR.
# If no files are specified, stages all changes (including untracked).
#
# Examples:
#   ./scripts/git-automate.sh feat/my-feature "feat: add new feature"
#   ./scripts/git-automate.sh fix/bug-123 "fix: resolve booking bug" src/components/File.tsx
#
# Requires: git, gh (GitHub CLI) — both must be authenticated.
#===============================================================================

set -euo pipefail

# ---- Colors ----
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ---- Help ----
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  sed -n '3,12p' "$0"
  exit 0
fi

# ---- Args ----
BRANCH="$1"
shift
COMMIT_MSG="$1"
shift
FILES=("$@")

# ---- Validate ----
if [[ -z "$BRANCH" || -z "$COMMIT_MSG" ]]; then
  echo -e "${RED}Usage:${NC} $0 <branch-name> <commit-message> [files...]"
  exit 1
fi

# ---- Step 1: Check git status ----
echo -e "${YELLOW}[1/5]${NC} Checking git status..."
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo -e "${RED}✖ Not a git repository${NC}"
  exit 1
fi

# ---- Step 2: Create and switch to branch ----
echo -e "${YELLOW}[2/5]${NC} Creating branch ${CYAN}$BRANCH${NC}..."
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo -e "${YELLOW}⚠ Branch already exists, switching to it${NC}"
  git checkout "$BRANCH"
else
  git checkout -b "$BRANCH"
fi

# ---- Step 3: Stage files ----
echo -e "${YELLOW}[3/5]${NC} Staging files..."
if [[ ${#FILES[@]} -eq 0 ]]; then
  # Stage all changes (including untracked)
  git add -A
  echo "  → Staged all changes"
else
  git add "${FILES[@]}"
  echo "  → Staged: ${FILES[*]}"
fi

# Check if anything is staged
if git diff --cached --quiet; then
  echo -e "${YELLOW}⚠ Nothing to commit. Exiting.${NC}"
  exit 0
fi

# ---- Step 4: Commit ----
echo -e "${YELLOW}[4/5]${NC} Committing..."
git commit -m "$COMMIT_MSG"
echo -e "${GREEN}✓ Committed:${NC} $(git log --oneline -1)"

# ---- Step 5: Push + PR ----
echo -e "${YELLOW}[5/5]${NC} Pushing and creating/updating PR..."
git push origin "$BRANCH" 2>&1

# Check for existing open PR on this head branch
EXISTING_PR=$(gh pr list --head "$BRANCH" --state open --json number,url --jq '.[0]' 2>/dev/null)

PR_BODY="Automated PR generated by \`scripts/git-automate.sh\`

## Summary
$COMMIT_MSG

## Changes
$(git log --oneline main..HEAD --format='- %s')"

if [[ -n "$EXISTING_PR" ]]; then
  PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.number')
  PR_URL=$(echo "$EXISTING_PR" | jq -r '.url')
  echo -e "${YELLOW}⚠ Existing PR found (#$PR_NUMBER), updating instead of creating new one${NC}"
  gh pr edit "$PR_NUMBER" --title "$COMMIT_MSG" --body "$PR_BODY" > /dev/null 2>&1
  echo ""
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  PR updated:${NC} $PR_URL"
  echo -e "${GREEN}  Branch:${NC}     $BRANCH"
  echo -e "${GREEN}  Commit:${NC}     $(git rev-parse --short HEAD)"
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
else
  PR_URL=$(gh pr create \
    --base main \
    --head "$BRANCH" \
    --title "$COMMIT_MSG" \
    --body "$PR_BODY" 2>&1)

  if [[ $? -eq 0 && -n "$PR_URL" ]]; then
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  PR created:${NC} $PR_URL"
    echo -e "${GREEN}  Branch:${NC}    $BRANCH"
    echo -e "${GREEN}  Commit:${NC}    $(git rev-parse --short HEAD)"
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
  else
    echo ""
    echo -e "${YELLOW}⚠ Push succeeded but PR creation failed.${NC}"
    echo -e "  Create PR manually: https://github.com/ettersAy/moussawer/pull/new/$BRANCH"
  fi
fi
