export {
  userResource,
  serviceResource,
  portfolioResource,
  photographerResource,
  bookingResource,
  messageResource,
  conversationResource,
  incidentResource,
  disputeResource,
  reviewResource,
  notificationResource,
  blockResource,
  projectResource,
} from "./resources/index";
